name: cash_ctrl
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  auto_route: any
  provider: any
  gap: any
  reactive_forms: any
  fl_chart: any
  pluto_grid: any
  random_avatar: any
  dartz: any
  dio: any
  flutter_launcher_icons: any
  get_it: any
  google_fonts: any
  otp_text_field: any
  shared_preferences: any
  image_picker: any
  image_editor_plus: any
  path_provider: any
  flutter_native_splash: any
  logger: any
  upi_payment_qrcode_generator: any
  injectable: any
  streaming_shared_preferences: any
  freezed_annotation: any
  json_annotation: any
  lottie: any
  jiffy: any
  ionicons: any
  expandable_menu: any
  flutter_expandable_fab: any
  syncfusion_flutter_charts: any
  syncfusion_flutter_datagrid: any
  qr_code_scanner: 1.0.0
  upi_india: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  auto_route_generator: any
  build_runner: any
  injectable_generator: any
  freezed: any
  json_serializable: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true
  assets:
    - splash_screen.json
    - assets/icon/icon.png